### ISSUE TITLE
Maintenance of CSS variables

### ISSUE THREAD

**Issue by AaronTDR** [AaronTDR/layout-building#19]
### Description
With the aim of keeping the code organized, it has been decided to reorganize the CSS variables so that their names make sense in different parts of the application.

### Tasks

- [x] Group by variable type, group the variables into sections based on their type or purpose. Separate sections for colors, typography, spacing, font sizes, margins, and padding. For example:

    ```css
    /* Colors */
    :root {
      --primary-color: #007bff;
      --secondary-color: #ff9900;
    }

    /* Typography */
    :root {
      --font-family: 'Roboto', sans-serif;
      --font-size-small: 14px;
    }
    ```

- [x] Alphabetical order: Within each section, arrange the variables alphabetically. This makes it easier to search for and reference specific variables. For example:

    ```css
    /* Colors */
    :root {
      --accent-color: #ff9900;
      --primary-color: #007bff;
    }

    /* Typography */
    :root {
      --font-family: 'Roboto', sans-serif;
      --font-size-small: 14px;
    }
    ```

- [x] Descriptive comments: Include descriptive comments for each group of variables to explain the purpose of the variables and provide useful documentation. For example:

    ```css
    /* Colors */
    :root {
      /* Main color used to highlight elements */
      --primary-color: #007bff;
      /* Accent color used to highlight secondary elements */
      --accent-color: #ff9900;
    }
    ```

### Considerations
- Try to maintain a global order before a local one. This will help establish a general context before addressing specific details.

**Comment by AaronTDR** [comment]
Issue tasks have been successfully completed!
