### ISSUE TITLE
Light and Dark Theme

### ISSUE THREAD

**Issue by AaronTDR** [AaronTDR/layout-building#23]
### Description:

Currently, the application lacks an interface that allows users to configure the color theme displayed on web elements. To enhance the user experience and provide a more user-friendly and customizable interface, we have decided to implement a system of light and dark themes.

### Context:

Our project follows a routing-based approach with 'react-router-dom'. This means we need to add the theme change at the highest level of the application, encompassing the entire application with a top-level component.

### Proposed Solution:

The proposed solution involves creating a component called 'ThemeProvider.' This component will be responsible for controlling the application's theme and will enable users to select a light or dark theme through a switch displayed in the application's header.

### Tasks:

- [x] Implement a 'ThemeProvider' component that manages the theme state (light or dark).
-  [x] Add a switch in the application's header so that users can switch between light and dark themes.
- [x] Ensure that the selected theme persists and remains consistent throughout the application, even when navigating between pages.
- [x] Provide appropriate CSS styles for the light and dark themes.
- [x] Ensure that the implementation is compatible with the versions of React and 'react-router-dom' that we are using.

### Detailed Implementation:

We need to implement a 'ThemeProvider' component that can provide the theme context to the application and allow child components to access this theme configuration.

```jsx
<ThemeProvider>
  {/* Entire application */}
</ThemeProvider>
```

Within the 'ThemeProvider' component, the theme state must be managed, and a function should be provided for switching between light and dark themes. Additionally, the theme should be applied through custom CSS styles.

**Comment by AaronTDR** [comment]
All issue requirements are met, ready for merge!
